### ISSUE TITLE
where is the data

### ISSUE THREAD

**Issue by AlexYoung757** [LunaBlack/RNN-Classification#1]
so where is the data ,such as labels.pkl ,vocab.pkl and corpus.txt

**Comment by LunaBlack** [comment]
You need to prepare dataset yourself.
Maybe, I will upload some testing data in a few days. I am testing my own dataset recently.

**Comment by AlexYoung757** [comment]
ok ，so i should also define the lablels.pkl 、vocab.pkl?

**Comment by LunaBlack** [comment]
Yes.
In my experiment, they are both dict. The key is original data, such as: for labels,  'A', 'B', 'C' or '01', '02'; for vocab, each char in corpus. The value is index from 0.
You can try it, and let me know if wrong.

**Comment by AlexYoung757** [comment]
thank you for asking my questio. i will try it later
well does it support chinese?

**Comment by LunaBlack** [comment]
Yes.
Actually, I do my experiment with Chinese corpus. I classify chinese books according to their titles.

**Comment by AlexYoung757** [comment]
wow , it's very cool . now i am also doing text classify for chinese . but the result seems not very good ,the acc is only about 50%.

**Comment by LunaBlack** [comment]
Under my model?

**Comment by AlexYoung757** [comment]
no , i  modify the code cnn-text-classification-tf-chinese ,and add rnn for embedding

**Comment by LunaBlack** [comment]
I have not compute accuracy of my dataset, so maybe my model is not good.
BTW, what text are you doing?

**Comment by AlexYoung757** [comment]
some short texts about news

**Comment by LunaBlack** [comment]
I upload some data. It contains more than 185,000 books belonging to 7 categories.
And, I add file 'cross_validation.py' to test data. In my experiment, the accuracy is about 88%.
For reference only.

**Comment by AlexYoung757** [comment]
干的漂亮。



375727119@qq.com
 
From: LunaBlack
Date: 2016-08-01 10:37
To: LunaBlack/RNN-Classification
CC: AlexYoung757; Author
Subject: Re: [LunaBlack/RNN-Classification] where is the data (#1)
I upload some data. It contains more than 185,000 books belonging to 7 categories.
And, I add file 'cross_validation.py' to test data. In my experiment, the accuracy is about 88%.
For reference only.
