### ISSUE TITLE
how about that if the inputs' steps are different?

### ISSUE THREAD

**Issue by xspring14** [LunaBlack/RNN-Classification#2]
could I ask you a question about the issue, what should I do when the inputs has a max_step_length, and each input's step is different but I still want the last valid output? Do you have a solution? Thank you!

**Comment by LunaBlack** [comment]
Sorry to answer you so late. Have you solved this issue?
In my project, I used the max length of all sequences as the length. If the length of sequence is shorter than it, I used a specified symbol to complete.
So, my program can not fit different length now. If you found how to do with it, welcome to discuss it with me.
