### ISSUE TITLE
def predict(args) run failed?

### ISSUE THREAD

**Issue by watchpoints** [LunaBlack/RNN-Classification#3]
Dimensions of inputs should match: shape[0] = [2,128] vs. shape[1] = [1,128]
	 [[Node: rnnLayer/MultiRNNCell/Cell0/BasicLSTMCell/Linear/concat = Concat[N=2, T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](rnnLayer/MultiRNNCell/Cell0/BasicLSTMCell/Linear/concat/concat_dim, embeddingLayer/Squeeze, zeros_1)]]

**Comment by LunaBlack** [comment]
Sorry, I could not understand what's wrong with your program according to your given information.
I guess, maybe your inputs of trainning and testing are different in dimensions?
