### ISSUE TITLE
about input data language

### ISSUE THREAD

**Issue by willduan** [LunaBlack/RNN-Classification#4]
我看到默认的是例子里面默认是中文，那样的话，代码里面是不是已经默认分词了？如果我输入的是英文的话，在input.csv里面应该谁什么格式呢？是不是这个样子就可以了
`thank you very mush, A`       (前面是句子，后面是label)
非常感谢！

**Comment by LunaBlack** [comment]
我的程序是基于字符的，char embedding，不是word embedding，所以不需要分词。
英文可以按你说的样子给格式，注意csv的分隔符就可以了。

**Comment by LunaBlack** [comment]
我最近重新整理了一下代码，对你的问题补充回答一下，虽然你可能已经不需要了。
如之前所说，我的程序是基于字符的，没有分词。
如果你用英文的话，如果不改代码，仍然是基于字符的，也就是单个字母、标点等。
如果你想基于词，需要自行添加分词程序，并且修改相应代码。
我在README.md里做了简单说明。

**Comment by willduan** [comment]
好的，非常感谢，可否继续完善一下代码，如提供基于词的和基于字符的。如果我有时间的话也会做点贡献(^-^)

**Comment by LunaBlack** [comment]
暂时不打算补充基于词的内容。
欢迎你做贡献～
