### ISSUE TITLE
no such file ： config.pkl

### ISSUE THREAD

**Issue by jiangyan12** [LunaBlack/RNN-Classification#5]
你好，
我在运行项目的时候报错缺少了config文件
我的配置是tensorflow1.1 ，python 2.8
报错内容：
    with open(os.path.join(args.save_dir, 'config.pkl'), 'wb') as f:
IOError: [Errno 2] No such file or directory: 'save/config.pkl'

**Comment by LunaBlack** [comment]
该文件是存储模型训练和测试的一些参数信息。
这个报错说明你没训练就开始测试或者再训练了。

**Comment by cailurus** [comment]
@jiangyan12 可能是因为需要 mkdir save/
