### ISSUE TITLE
关于替换csv文件的问题

### ISSUE THREAD

**Issue by dzwduan** [LunaBlack/RNN-Classification#8]
[数据导出 - 副本.xlsx](https://github.com/LunaBlack/RNN-Classification/files/1141244/-.xlsx)
这份文件存在多处重复，但重复项对应的label不尽相同，我是否应该将重复语句全部录入语料模型；还是去重之后录入，但label可能会有变化，谢谢指教==W==

**Comment by LunaBlack** [comment]
这取决于你想干什么，具体任务怎样

**Comment by dzwduan** [comment]
[数据导出.xlsx](https://github.com/LunaBlack/RNN-Classification/files/1141309/default.xlsx)
具体任务是给定一句话，判断它所属的两个标签，上面是完整文档，我准备将它分成两个文件，分别读入各自的label,然后进行输出汇总

**Comment by LunaBlack** [comment]
我的意思是取决于你任务的具体要求，各指标要求等等

**Comment by dzwduan** [comment]
。。。没有说明具体要求，只要求预测正确率

**Comment by LunaBlack** [comment]
人工核对也可以，全部直接输入也可以。
还是那句话，取决于你自己的任务情况。

**Comment by dzwduan** [comment]
好的，我都试一下看准确率，谢谢老铁
