### ISSUE TITLE
关于文件之间的关系

### ISSUE THREAD

**Issue by dzwduan** [LunaBlack/RNN-Classification#9]
1.data.csv和语料库corpus.text都是提前放进去的吗
2.data.csv的生成是用corpus.text产生的吗
3.train.py中有这样一段代码
parser.add_argument('--utils_dir', type=str, default='utils',
                        help='''directory containing labels.pkl and corpus.txt:
                        'corpus.txt'      : corpus to define vocabulary;
                        'vocab.pkl'       : vocabulary definitions;
                        'labels.pkl'      : label definitions''')
utils文件夹的作用是什么，corpus.txt,vocab.pkl,label.pkl三者之间有什么联系吗
多谢指导

**Comment by LunaBlack** [comment]
请看readme

**Comment by dzwduan** [comment]
好的
